//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsCommande
    {
        public int Num_cmd { get; set; }
        public int RefProduit { get; set; }
        public int Quantite { get; set; }
        public string CIN { get; set; }
    
        public virtual client client { get; set; }
        public virtual Commande Commande { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
