//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplGestion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionCommande : DbContext
    {
        public GestionCommande()
            : base("name=GestionCommande")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<connextion> connextion { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<DetailsCommande> DetailsCommande { get; set; }
    }
}
