//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        internal int nextRefproduit;
        internal string intitule;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.DetailsCommande = new HashSet<DetailsCommande>();
        }
    
        public int Refproduit { get; set; }
        //public string RefProduit { get; internal set; }
        public string Intitule { get; set; }
        public string Categorie { get; set; }
        public Nullable<decimal> PrixVente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsCommande> DetailsCommande { get; set; }

        //public static implicit operator Produit(Produit v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}
